import tkinter as tk

def insertar_texto():
    cuadro_texto.insert(tk.END,"Albion online es un mmorpg no lineal en el que escribes tu propia historia sin limitarte a seguir un camino prefijado, explora un amplio mundo abierto con cinco biomas unicos, todo cuanto hagas tendra su repercusíon en el mundo, con su economia orientada al jugador de albion los jugadores crean practicamente todo el equipo a partir de los recursos que consiguen, el equipo que llevas define quien eres, cambia de arma y armadura para pasar de caballero a mago o juego como una mezcla de ambas clases."
                               "\nAventurate en el mundo abierto y haz frente a los habitantes y las criaturas de albion, inicia expediciones o adentrate en mazmorras en las que encontraras enemigos aun mas dificiles, enfrentate a otros jugadores en encuentros en el mundo abierto, lucha por los territorios o por ciudades enteras en batallas tacticas, relajate en tu isla privada donde podras construir un hogar, cultivar cosechas, criar animales, unete a un gremio, todo es mejor cuando se trabaja en grupo [musica] adentrate ya en el mundo de albion y escribe tu propia historia."
                               "\n\nAlbion Online is a non-linear MMORPG in which you write your own story without being limited to following a predetermined path. Explore a vast open world with five unique biomes. Everything you do will have an impact on the world. With Albion's player-oriented economy, players create virtually all of their equipment from the resources they obtain. The equipment you wear defines who you are. Change your weapons and armor to go from knight to mage or play as a mix of both classes."
                               "\nVenture into the open world and face the inhabitants and creatures of Albion. Embark on expeditions or delve into dungeons where you'll find even more difficult enemies. Face other players in open-world encounters. fight for territories or entire cities in tactical battles, relax on your private island where you can build a home, grow crops, raise animals, join a guild, everything is better when you work as a team [music] enter the world of Albion now and write your own story."
                               "\n\n「Albion Online」は、あらかじめ決められた道筋に従うことなく、自分自身の物語を紡ぐことができるノンリニア型MMORPGです。5つのユニークなバイオームからなる広大なオープンワールドを探索し、プレイヤーの行動はすべて世界に影響を与えます。Albionのプレイヤー主導型経済では、プレイヤーは入手した資源からほぼすべての装備を自ら作成します。装備はプレイヤーのアイデンティティを定義します。武器や防具を交換して騎士から魔法使いへ、あるいは両方のクラスを組み合わせたプレイスタイルへ変化させましょう。"
                               "\nオープンワールドに冒険に出て、アルビオンの住民やクリーチャーに立ち向かい、遠征に出かけ、さらに手強い敵が待つダンジョンに挑みましょう。オープンワールドでの遭遇戦で他のプレイヤーと対決し、 領土や都市全体を賭けた戦術的な戦い、プライベートアイランドでくつろぎながら家を建て、作物を育て、動物を飼育、ギルドに加入、チームワークで全てがより良くなる[音楽]今すぐアルビオンの世界に飛び込み、あなた自身の物語を刻み込もう。」"
                               "\n\nAlbion Online ist ein nichtlineares MMORPG, in dem Sie Ihre eigene Geschichte schreiben, ohne einem vorgegebenen Weg folgen zu müssen. Erkunden Sie eine weitläufige offene Welt mit fünf einzigartigen Biomen. alles, was du tust, hat Auswirkungen auf die Welt. Dank der spielerorientierten Wirtschaft von Albion stellen die Spieler praktisch ihre gesamte Ausrüstung aus den Ressourcen her, die sie finden. Die Ausrüstung, die du trägst, definiert, wer du bist. Wechsle Waffen und Rüstungen, um vom Ritter zum Magier zu werden, oder spiele als eine Mischung aus beiden Klassen."
                               "\nBegeben Sie sich in die offene Welt und stellen Sie sich den Bewohnern und Kreaturen von Albion, starten Sie Expeditionen oder begeben Sie sich in Dungeons, in denen Sie noch schwierigere Gegner finden, treten Sie anderen Spielern in Begegnungen in der offenen Welt entgegen, kämpfe in taktischen Schlachten um Gebiete oder ganze Städte, entspanne dich auf deiner privaten Insel, wo du ein Zuhause bauen, Getreide anbauen und Tiere züchten kannst, tritt einer Gilde bei, alles ist besser, wenn man in der Gruppe arbeitet [Musik] tauche jetzt in die Welt von Albion ein und schreibe deine eigene Geschichte."
                               "\n\nAlbion Online est un MMORPG non linéaire dans lequel vous écrivez votre propre histoire sans vous limiter à suivre un chemin prédéfini. Explorez un vaste monde ouvert avec cinq biomes uniques. tout ce que vous faites aura un impact sur le monde. Grâce à l'économie orientée vers le joueur d'Albion, les joueurs créent pratiquement tout leur équipement à partir des ressources qu'ils obtiennent. L'équipement que vous portez définit qui vous êtes. Changez d'arme et d'armure pour passer de chevalier à magicien ou jouez comme un mélange des deux classes."
                               "\nAventurez-vous dans le monde ouvert et affrontez les habitants et les créatures d'Albion, lancez des expéditions ou explorez des donjons où vous rencontrerez des ennemis encore plus difficiles, affrontez d'autres joueurs dans des combats en monde ouvert, battez-vous pour des territoires ou des villes entières dans des batailles tactiques, détendez-vous sur votre île privée où vous pourrez construire une maison, cultiver des récoltes, élever des animaux, rejoindre une guilde, tout est mieux quand on travaille en groupe [musique] plongez dès maintenant dans le monde d'Albion et écrivez votre propre histoire."
                               "\n\n《Albion Online》是一款非線性MMORPG，玩家能書寫屬於自己的故事，無需拘泥於既定路線。探索廣闊的開放世界，其中包含五種獨特的生物群系， 你的每項行動都將影響世界走向。在以玩家為導向的經濟體系中，玩家幾乎能運用獲取的資源打造所有裝備，而裝備定義了你的身份——更換武器與盔甲即可從騎士轉為法師，或同時兼具兩者特質。"
                               "\n踏入開放世界，與艾伯倫的居民與生物互動；發起遠征或深入地牢挑戰更強敵人；在開放世界遭遇戰中與其他玩家交鋒； 為領土或整座城市展開戰術對決，在私人島嶼上建造家園、耕種作物、飼養牲畜，加入公會——團隊合作讓一切更美好[音樂]。即刻踏入艾伯倫世界，書寫屬於你的傳奇。」"
                               "\n\n앨비언 온라인은 미리 정해진 길을 따르지 않고 자신의 이야기를 직접 써나가는 비선형 MMORPG입니다. 다섯 가지 독특한 생물군계를 지닌 광활한 오픈 월드를 탐험하세요. 당신이 하는 모든 행동은 세계에 영향을 미칩니다. 플레이어 중심의 경제 시스템으로, 플레이어는 획득한 자원을 활용해 거의 모든 장비를 직접 제작합니다. 착용한 장비가 당신의 정체성을 정의합니다. 무기와 방어구를 바꿔 기사에서 마법사로, 혹은 두 직업을 혼합한 방식으로 플레이하세요."
                               "\n오픈 월드에 모험을 떠나 알비온의 주민들과 생물들을 상대하세요. 탐험을 시작하거나 더 강력한 적들이 기다리는 던전에 도전하세요. 오픈 월드에서 다른 플레이어들과 맞서 싸우거나, 영토나 도시 전체를 걸고 전술 전투를 벌이거나, 개인 섬에서 집을 짓고 농작물을 재배하며 동물을 기르며 휴식을 취하세요. 길드에 가입하세요. 함께할 때 모든 것이 더 좋습니다. [음악] 지금 바로 앨비언의 세계로 들어가 여러분만의 이야기를 써 내려가세요."
                               "\n\nAlbion Online é um MMORPG não linear no qual você escreve a sua própria história sem se limitar a seguir um caminho pré-definido. Explore um vasto mundo aberto com cinco biomas únicos. tudo o que fizer terá repercussões no mundo. Com a sua economia orientada para o jogador, os jogadores criam praticamente todo o equipamento a partir dos recursos que obtêm. O equipamento que usa define quem é. Mude de arma e armadura para passar de cavaleiro a mago ou jogue como uma mistura de ambas as classes."
                               "\nAventure-se no mundo aberto e enfrente os habitantes e criaturas de Albion, inicie expedições ou entre em masmorras onde encontrará inimigos ainda mais difíceis, enfrente outros jogadores em encontros no mundo aberto, lute por territórios ou cidades inteiras em batalhas táticas, relaxe na sua ilha privada onde poderá construir uma casa, cultivar colheitas, criar animais, junte-se a um clã, tudo é melhor quando se trabalha em grupo [música] entre agora no mundo de Albion e escreva a sua própria história."
                               "\n\nAlbion Online — это нелинейная MMORPG, в которой вы пишете свою собственную историю, не ограничиваясь заданным путем, исследуете обширный открытый мир с пятью уникальными биомами, все, что вы делаете, будет иметь последствия для мира. Благодаря ориентированной на игроков экономике Albion, игроки создают практически все снаряжение из добытых ресурсов. Ваше снаряжение определяет, кем вы являетесь. Меняйте оружие и доспехи, чтобы превратиться из рыцаря в мага или играть как смесь обоих классов»."
                               "\nОтправляйтесь в открытый мир и сражайтесь с жителями и существами Альбиона, отправляйтесь в экспедиции или проникайте в подземелья, где вы встретите еще более сложных врагов, сражайтесь с другими игроками в открытом мире, сражайтесь за территории или целые города в тактических сражениях, отдыхайте на своем частном острове, где вы сможете построить дом, выращивать урожай, разводить животных, присоединяйтесь к гильдии, все лучше, когда работаешь в группе [музыка] погрузитесь в мир Альбиона и напишите свою собственную историю"
                               "\n\nAlbion Online è un MMORPG non lineare in cui scrivi la tua storia senza limitarti a seguire un percorso prestabilito, esplori un vasto mondo aperto con cinque biomi unici, tutto ciò che fai avrà un impatto sul mondo. Con la sua economia orientata al giocatore, i giocatori di Albion creano praticamente tutto l'equipaggiamento dalle risorse che ottengono. L'equipaggiamento che indossi definisce chi sei: cambia arma e armatura per passare da cavaliere a mago o gioca come un mix di entrambe le classi."
                               "\nAvventurati nel mondo aperto e affronta gli abitanti e le creature di Albion, intraprendi spedizioni o addentrati in dungeon dove troverai nemici ancora più difficili, affronta altri giocatori in incontri nel mondo aperto, combatti per i territori o per intere città in battaglie tattiche, rilassati sulla tua isola privata dove potrai costruire una casa, coltivare raccolti, allevare animali, unirti a una gilda, tutto è meglio quando si lavora in gruppo [musica] entra subito nel mondo di Albion e scrivi la tua storia.")

#Crear la ventana principal
root = tk.Tk()
root.title("Ejercicio 10: Scrollbar")
root.geometry("300x300")

#Crear un frame para contener el text y las scrollbars
frame = tk.Frame(root)
frame.pack(fill='both', expand=True)

#Crear el text
cuadro_texto = tk.Text(frame, wrap='word')
cuadro_texto.grid(row=0, column=0, sticky='nsew')

#Crear scrollbar vertical
scroll_vert = tk.Scrollbar(frame, orient='vertical', command=cuadro_texto.yview)
scroll_vert.grid(row=0, column=1, sticky='ns') #Alineamos a la derecha del Text
cuadro_texto.config(yscrollcommand=scroll_vert.set)

#Ajustar el tamaño de frame y el text al tamaño de la ventana
frame.grid_rowconfigure(0, weight=1)
frame.grid_columnconfigure(0, weight=1)

insertar_texto()

#Ejecutar el bucle principal
root.mainloop()